default:
  tags:
    - CREMI 
    - Focal/Fossa

stages:
  - build
  - test
  - coverage

buid-job1:
  stage: build
  script :
    - pip install coverage

test-FileRepo:
  stage: test
  script :
    - python3 -m unittest -v tests/test_FileRepo.py
    
test-Point:
  stage: test
  script :
    - python3 -m unittest -v tests/test_Point.py

test-Graph:
  stage: test
  script :
    - python3 -m unittest -v tests/test_Graph.py
    
coverage-FileRepo:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run -m pytest tests/test_FileRepo.py
    - coverage report -m

coverage-Point:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run -m pytest tests/test_Point.py
    - coverage report -m

coverage-Graph:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run -m pytest tests/test_Graph.py
    - coverage report -m
